### ISSUE TITLE
urllibのエラー

### ISSUE THREAD

**Issue by KenYMG** [KatsuhiroMorishita/AMeDAS_downloader#1]
はじめまして、cloneして、まずはそのままdownloader.py　"10min"　を
実行したのですが、下記のエラーが出力されます。

```
Traceback (most recent call last):
  File "download.py", line 13, in <module>
    import urllib.request
ImportError: No module named request
```

import urllib.requestをimport urllibに書き換えるとそこは回避できるのですが、
下記のエラーが出力されます。Pythonのバージョン依存などあるのでしょうか？

```
Traceback (most recent call last):
  File "download.py", line 207, in <module>
    main()
  File "download.py", line 163, in main
    amedas_nodes = get_amedas_nodes()
  File "download.py", line 107, in get_amedas_nodes
    with open(fname, "r", encoding="utf-8-sig") as fr:
TypeError: 'encoding' is an invalid keyword argument for this function
```

環境
windows 8 python 2.7.11
windows10 python 2.7.11

**Comment by KenYMG** [comment]
ごめんなさい。
Python3が前提なのですね。Issueは取り下げさせていただきます。

**Comment by KatsuhiroMorishita** [comment]
利用してもらって嬉しいです。そう、Python3専用なんです。笑

**Comment by KatsuhiroMorishita** [comment]
とじます
